source:
  profile:
    git_repository: git@github.com:Vardot/varbase_subprofile_basic.git
    dev_branch:
      name: 9.0.x
      alias: 9.0.x-dev
      label: 9.0.x
  project:
    git_repository: git@github.com:Vardot/varbase-subprofile-basic-project.git
    dev_branch:
      name: 9.0.x
      alias: 9.0.x-dev
      label: 9.0.x
target:
  profile:
    dev_branch:
      name: 1.0.x
      alias: 1.0.x-dev
      label: 1.0.x
  project:
    dev_branch:
      name: 1.0.x
      alias: 1.0.x-dev
      label: 1.0.x
profile_dir_list:
  - /
  - /config/install
  - /configbit
  - /modules
  - /images
  - /js
  - /css
  - /modules/SUB_PROFILE_NAME_demo
  - /modules/SUB_PROFILE_NAME_features
  - /modules/SUB_PROFILE_NAME_features/SUB_PROFILE_NAME_homepage
  - /modules/SUB_PROFILE_NAME_features/SUB_PROFILE_NAME_homepage/config/install
project_dir_list:
  - /
rename_file_list:
  - varbase_subprofile_basic
  - varbase-subprofile-basic
replace_string_list:
  - varbase_subprofile_basic
  - varbase-subprofile-basic
  - Varbase Sub Profile Basic
  - Varbase Subprofile
  - Varbase Sub Profile Basic Project
  - VARBASE_SUBPROFILE_BASIC
  - varbase sub profile basic